/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oliva
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;

import java.util.*;

public class welcome extends javax.swing.JFrame {


    private javax.swing.Timer time = new javax.swing.Timer(1000, displayTime());
    private java.util.Date now;
    private javax.swing.Timer date = new javax.swing.Timer(1000, displayTime());

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loadingnum = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        christmasLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Kyoto = new javax.swing.JLabel();
        loadLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(63, 72, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KYOTO UNIVERSITY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 581, 90));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Record System by: Asian Institute of Computer Studies");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 500, 30));

        jLabel3.setBackground(new java.awt.Color(60, 72, 204));
        jLabel3.setForeground(new java.awt.Color(60, 72, 204));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        loadingnum.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        loadingnum.setForeground(new java.awt.Color(255, 255, 255));
        loadingnum.setText("0%");
        jPanel1.add(loadingnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 40));

        loadingbar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 480, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Developed by: Team Pogi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        christmasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/santa-hat-clipart-transparent-.png"))); // NOI18N
        jPanel1.add(christmasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Kyoto University.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 120));

        Kyoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/京都大学.png"))); // NOI18N
        jPanel1.add(Kyoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 30));

        loadLabel.setText("Loading Scripts....");
        jPanel1.add(loadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("version 0.1.1 beta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        timeLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));

        dateLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(660, 276));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        time.start();
        date.start();
    }//GEN-LAST:event_formWindowOpened
    public Action displayTime() {
        return new AbstractAction("Time") {

            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat stf = new SimpleDateFormat("HH:mm:ss");

                now = new java.util.Date();
                timeLabel.setText(stf.format(now));
                SimpleDateFormat s=new SimpleDateFormat("MM-dd-yyyy-EEEE");
                dateLabel.setText(s.format(now));
            }
        };
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                   
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kyoto;
    private javax.swing.JLabel christmasLabel;
    public javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel loadLabel;
    public javax.swing.JProgressBar loadingbar;
    public javax.swing.JLabel loadingnum;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
